# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'JRMainDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JRMainDemo

  pod 'JRSubDemo', :path => '/Users/jiangshulun/JRMainSubDemo/JRSubProject/JRSubDemo'

end
